spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bank_app
    username: dbuser
    password: dbpass
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            cache:
              uri: classpath:jcache.xml
  liquibase:
    changeLog: db.changelog/changeLog.yaml
    contexts: default
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false


jwt:
  secret: meshgroup
  tokenExpirationDays: 100

scheduled:
  balanceUpdateInterval: 3000
  increaseRate: "1.1"

logging:
  level:
    root: DEBUG
    o.s.s.web.DefaultSecurityFilterChain: WARN
    org.hibernate.cache: INFO
    org.hibernate.type: TRACE

springdoc:
  swagger-ui:
    tagsSorter: alpha