spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bank_app
    username: dbuser
    password: dbpass
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            cache:
              uri: classpath:jcache.xml
  liquibase:
    changeLog: db.changelog/changeLog.yaml
    contexts: default

jwt:
  secret: meshgroup

scheduled:
  balanceUpdateDelay: 3000

logging:
  level:
    root: INFO
    o.s.s.web.DefaultSecurityFilterChain: WARN
    org.hibernate.cache: INFO
    org.hibernate.type: TRACE