version: "3.8"
services:
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - ./db.changelog/init/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis-service:
    image: "redis:alpine"
    ports:
      - "6379:6379"